---
deployment:
  tasks:
    # Deploy child theme
    - /bin/cp -r wp-content/themes/alwayshere-child /home/bestsale/public_html/wp-content/themes/alwayshere-child
    # Deploy custom plugin
    - /bin/cp -r wp-content/plugins/alwayshere-core /home/bestsale/public_html/wp-content/plugins/alwayshere-core
